//
// Home.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Home: Codable {

    public var title: String
    public var _description: String
    public var price: String
    public var bedrooms: Int
    public var bathrooms: Int
    public var area: String
    public var address: String
    public var createdAt: Date

    public init(title: String, _description: String, price: String, bedrooms: Int, bathrooms: Int, area: String, address: String, createdAt: Date) {
        self.title = title
        self._description = _description
        self.price = price
        self.bedrooms = bedrooms
        self.bathrooms = bathrooms
        self.area = area
        self.address = address
        self.createdAt = createdAt
    }

    public enum CodingKeys: String, CodingKey { 
        case title
        case _description = "description"
        case price
        case bedrooms
        case bathrooms
        case area
        case address
        case createdAt = "created_at"
    }

}
