//
// PatchedHome.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PatchedHome: Codable {

    public var _id: Int?
    public var title: String?
    public var _description: String?
    public var price: String?
    public var bedrooms: Int?
    public var bathrooms: Int?
    public var area: String?
    public var address: String?
    public var createdAt: Date?

    public init(_id: Int? = nil, title: String? = nil, _description: String? = nil, price: String? = nil, bedrooms: Int? = nil, bathrooms: Int? = nil, area: String? = nil, address: String? = nil, createdAt: Date? = nil) {
        self._id = _id
        self.title = title
        self._description = _description
        self.price = price
        self.bedrooms = bedrooms
        self.bathrooms = bathrooms
        self.area = area
        self.address = address
        self.createdAt = createdAt
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case title
        case _description = "description"
        case price
        case bedrooms
        case bathrooms
        case area
        case address
        case createdAt = "created_at"
    }

}
