//
// CustomSerialier.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct CustomSerialier: Codable {

    public var name: String
    public var lastName: String
    public var age: Int
    public var email: String
    public var phone: String
    public var address: String
    public var _description: String
    public var date: Date

    public init(name: String, lastName: String, age: Int, email: String, phone: String, address: String, _description: String, date: Date) {
        self.name = name
        self.lastName = lastName
        self.age = age
        self.email = email
        self.phone = phone
        self.address = address
        self._description = _description
        self.date = date
    }

    public enum CodingKeys: String, CodingKey { 
        case name
        case lastName = "last_name"
        case age
        case email
        case phone
        case address
        case _description = "description"
        case date
    }

}
