//
// TokenObtainPair.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct TokenObtainPair: Codable {

    public var username: String
    public var password: String
    public var access: String
    public var refresh: String

    public init(username: String, password: String, access: String, refresh: String) {
        self.username = username
        self.password = password
        self.access = access
        self.refresh = refresh
    }


}
