//
// Report.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Report: Codable {

    public var title: String
    public var descripcion: String
    public var fecha: Date

    public init(title: String, descripcion: String, fecha: Date) {
        self.title = title
        self.descripcion = descripcion
        self.fecha = fecha
    }


}
