//
// Car.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Car: Codable {

    public var brand: String
    public var specifications: String
    public var createdAt: Date

    public init(brand: String, specifications: String, createdAt: Date) {
        self.brand = brand
        self.specifications = specifications
        self.createdAt = createdAt
    }

    public enum CodingKeys: String, CodingKey {
        case brand
        case specifications
        case createdAt = "created_at"
    }

}
