//
// HomeAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire


open class HomeAPI {
    /**

     - parameter body: (body)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func homeCreate(body: Car, completion: @escaping ((_ data: Car?,_ error: Error?) -> Void)) {
        homeCreateWithRequestBuilder(body: body).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     - POST /home/

     - BASIC:
       - type: http
       - name: basicAuth
     - API Key:
       - type: apiKey sessionid (QUERY)
       - name: cookieAuth
     - examples: [{contentType=application/json, example={
  "created_at" : "2000-01-23",
  "brand" : "brand",
  "specifications" : "specifications"
}}]
     - parameter body: (body)

     - returns: RequestBuilder<Car>
     */
    open class func homeCreateWithRequestBuilder(body: Car) -> RequestBuilder<Car> {
        let path = "/home/"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: body)
        let url = URLComponents(string: URLString)


        let requestBuilder: RequestBuilder<Car>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }
    /**

     - parameter brand2: (form)
     - parameter specifications2: (form)
     - parameter createdAt2: (form)
     - parameter brand: (form)
     - parameter specifications: (form)
     - parameter createdAt: (form)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func homeCreate(brand2: String, specifications2: String, createdAt2: Date, brand: String, specifications: String, createdAt: Date, completion: @escaping ((_ data: Car?,_ error: Error?) -> Void)) {
        homeCreateWithRequestBuilder(brand2: brand2, specifications2: specifications2, createdAt2: createdAt2, brand: brand, specifications: specifications, createdAt: createdAt).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     - POST /home/

     - BASIC:
       - type: http
       - name: basicAuth
     - API Key:
       - type: apiKey sessionid (QUERY)
       - name: cookieAuth
     - examples: [{contentType=application/json, example={
  "created_at" : "2000-01-23",
  "brand" : "brand",
  "specifications" : "specifications"
}}]
     - parameter brand2: (form)
     - parameter specifications2: (form)
     - parameter createdAt2: (form)
     - parameter brand: (form)
     - parameter specifications: (form)
     - parameter createdAt: (form)

     - returns: RequestBuilder<Car>
     */
    open class func homeCreateWithRequestBuilder(brand2: String, specifications2: String, createdAt2: Date, brand: String, specifications: String, createdAt: Date) -> RequestBuilder<Car> {
        let path = "/home/"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: {})
        let url = URLComponents(string: URLString)


        let requestBuilder: RequestBuilder<Car>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }
    /**

     - parameter brand2: (form)
     - parameter specifications2: (form)
     - parameter createdAt2: (form)
     - parameter brand: (form)
     - parameter specifications: (form)
     - parameter createdAt: (form)
     - parameter completion: completion handler to receive the data and the error objects
     */



    /**
     - POST /home/

     - BASIC:
       - type: http
       - name: basicAuth
     - API Key:
       - type: apiKey sessionid (QUERY)
       - name: cookieAuth
     - examples: [{contentType=application/json, example={
  "created_at" : "2000-01-23",
  "brand" : "brand",
  "specifications" : "specifications"
}}]
     - parameter brand2: (form)
     - parameter specifications2: (form)
     - parameter createdAt2: (form)
     - parameter brand: (form)
     - parameter specifications: (form)
     - parameter createdAt: (form)

     - returns: RequestBuilder<Car>
     */

    /**

     - parameter _id: (path) A unique integer value identifying this car sale.
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func homeDestroy(_id: Int, completion: @escaping ((_ data: Void?,_ error: Error?) -> Void)) {
        homeDestroyWithRequestBuilder(_id: _id).execute { (response, error) -> Void in
            if error == nil {
                completion((), error)
            } else {
                completion(nil, error)
            }
        }
    }


    /**
     - DELETE /home/{id}/

     - BASIC:
       - type: http
       - name: basicAuth
     - API Key:
       - type: apiKey sessionid (QUERY)
       - name: cookieAuth
     - parameter _id: (path) A unique integer value identifying this car sale.

     - returns: RequestBuilder<Void>
     */
    open class func homeDestroyWithRequestBuilder(_id: Int) -> RequestBuilder<Void> {
        var path = "/home/{id}/"
        let _idPreEscape = "\(_id)"
        let _idPostEscape = _idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{id}", with: _idPostEscape, options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        let url = URLComponents(string: URLString)


        let requestBuilder: RequestBuilder<Void>.Type = SwaggerClientAPI.requestBuilderFactory.getNonDecodableBuilder()

        return requestBuilder.init(method: "DELETE", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }
    /**

     - parameter page: (query) A page number within the paginated result set. (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func homeList(page: Int? = nil, completion: @escaping ((_ data: PaginatedCarList?,_ error: Error?) -> Void)) {
            let username = "A01661894"
            let password = "jony123"
            let loginString = "\(username):\(password)"
            let loginData = loginString.data(using: .utf8)!
            let base64LoginString = loginData.base64EncodedString()

            homeListWithRequestBuilder(page: page)
                .addHeader(name: "Authorization", value: "Basic \(base64LoginString)")
                .execute { (response, error) -> Void in
                completion(response?.body, error)
            }
        }


    /**
     - GET /home/

     - BASIC:
       - type: http
       - name: basicAuth
     - API Key:
       - type: apiKey sessionid (QUERY)
       - name: cookieAuth
     - examples: [{contentType=application/json, example={
  "next" : "http://api.example.org/accounts/?page=4",
  "previous" : "http://api.example.org/accounts/?page=2",
  "count" : 123,
  "results" : [ {
    "created_at" : "2000-01-23",
    "brand" : "brand",
    "specifications" : "specifications"
  }, {
    "created_at" : "2000-01-23",
    "brand" : "brand",
    "specifications" : "specifications"
  } ]
}}]
     - parameter page: (query) A page number within the paginated result set. (optional)

     - returns: RequestBuilder<PaginatedCarList>
     */
    open class func homeListWithRequestBuilder(page: Int? = nil) -> RequestBuilder<PaginatedCarList> {
        let path = "/home/"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
                        "page": page?.encodeToJSON()
        ])


        let requestBuilder: RequestBuilder<PaginatedCarList>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }
    /**

     - parameter _id: (path) A unique integer value identifying this car sale.
     - parameter body: (body)  (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func homePartialUpdate(_id: Int, body: PatchedCar? = nil, completion: @escaping ((_ data: Car?,_ error: Error?) -> Void)) {
        homePartialUpdateWithRequestBuilder(_id: _id, body: body).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     - PATCH /home/{id}/

     - BASIC:
       - type: http
       - name: basicAuth
     - API Key:
       - type: apiKey sessionid (QUERY)
       - name: cookieAuth
     - examples: [{contentType=application/json, example={
  "created_at" : "2000-01-23",
  "brand" : "brand",
  "specifications" : "specifications"
}}]
     - parameter _id: (path) A unique integer value identifying this car sale.
     - parameter body: (body)  (optional)

     - returns: RequestBuilder<Car>
     */
    open class func homePartialUpdateWithRequestBuilder(_id: Int, body: PatchedCar? = nil) -> RequestBuilder<Car> {
        var path = "/home/{id}/"
        let _idPreEscape = "\(_id)"
        let _idPostEscape = _idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{id}", with: _idPostEscape, options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: body)
        let url = URLComponents(string: URLString)


        let requestBuilder: RequestBuilder<Car>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "PATCH", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }
    /**

     - parameter _id: (path) A unique integer value identifying this car sale.
     - parameter brand2: (form)  (optional)
     - parameter specifications2: (form)  (optional)
     - parameter createdAt2: (form)  (optional)
     - parameter brand: (form)  (optional)
     - parameter specifications: (form)  (optional)
     - parameter createdAt: (form)  (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func homePartialUpdate(_id: Int, brand2: String? = nil, specifications2: String? = nil, createdAt2: Date? = nil, brand: String? = nil, specifications: String? = nil, createdAt: Date? = nil, completion: @escaping ((_ data: Car?,_ error: Error?) -> Void)) {
        homePartialUpdateWithRequestBuilder(_id: _id, brand2: brand2, specifications2: specifications2, createdAt2: createdAt2, brand: brand, specifications: specifications, createdAt: createdAt).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     - PATCH /home/{id}/

     - BASIC:
       - type: http
       - name: basicAuth
     - API Key:
       - type: apiKey sessionid (QUERY)
       - name: cookieAuth
     - examples: [{contentType=application/json, example={
  "created_at" : "2000-01-23",
  "brand" : "brand",
  "specifications" : "specifications"
}}]
     - parameter _id: (path) A unique integer value identifying this car sale.
     - parameter brand2: (form)  (optional)
     - parameter specifications2: (form)  (optional)
     - parameter createdAt2: (form)  (optional)
     - parameter brand: (form)  (optional)
     - parameter specifications: (form)  (optional)
     - parameter createdAt: (form)  (optional)

     - returns: RequestBuilder<Car>
     */
    open class func homePartialUpdateWithRequestBuilder(_id: Int, brand2: String? = nil, specifications2: String? = nil, createdAt2: Date? = nil, brand: String? = nil, specifications: String? = nil, createdAt: Date? = nil) -> RequestBuilder<Car> {
        var path = "/home/{id}/"
        let _idPreEscape = "\(_id)"
        let _idPostEscape = _idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{id}", with: _idPostEscape, options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: {})
        let url = URLComponents(string: URLString)


        let requestBuilder: RequestBuilder<Car>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "PATCH", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }
    /**

     - parameter _id: (path) A unique integer value identifying this car sale.
     - parameter brand2: (form)  (optional)
     - parameter specifications2: (form)  (optional)
     - parameter createdAt2: (form)  (optional)
     - parameter brand: (form)  (optional)
     - parameter specifications: (form)  (optional)
     - parameter createdAt: (form)  (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */



    /**
     - PATCH /home/{id}/

     - BASIC:
       - type: http
       - name: basicAuth
     - API Key:
       - type: apiKey sessionid (QUERY)
       - name: cookieAuth
     - examples: [{contentType=application/json, example={
  "created_at" : "2000-01-23",
  "brand" : "brand",
  "specifications" : "specifications"
}}]
     - parameter _id: (path) A unique integer value identifying this car sale.
     - parameter brand2: (form)  (optional)
     - parameter specifications2: (form)  (optional)
     - parameter createdAt2: (form)  (optional)
     - parameter brand: (form)  (optional)
     - parameter specifications: (form)  (optional)
     - parameter createdAt: (form)  (optional)

     - returns: RequestBuilder<Car>
     */

    /**

     - parameter _id: (path) A unique integer value identifying this car sale.
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func homeRetrieve(_id: Int, completion: @escaping ((_ data: Car?,_ error: Error?) -> Void)) {
        homeRetrieveWithRequestBuilder(_id: _id).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     - GET /home/{id}/

     - BASIC:
       - type: http
       - name: basicAuth
     - API Key:
       - type: apiKey sessionid (QUERY)
       - name: cookieAuth
     - examples: [{contentType=application/json, example={
  "created_at" : "2000-01-23",
  "brand" : "brand",
  "specifications" : "specifications"
}}]
     - parameter _id: (path) A unique integer value identifying this car sale.

     - returns: RequestBuilder<Car>
     */
    open class func homeRetrieveWithRequestBuilder(_id: Int) -> RequestBuilder<Car> {
        var path = "/home/{id}/"
        let _idPreEscape = "\(_id)"
        let _idPostEscape = _idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{id}", with: _idPostEscape, options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        let url = URLComponents(string: URLString)


        let requestBuilder: RequestBuilder<Car>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }
    /**

     - parameter body: (body)
     - parameter _id: (path) A unique integer value identifying this car sale.
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func homeUpdate(body: Car, _id: Int, completion: @escaping ((_ data: Car?,_ error: Error?) -> Void)) {
        homeUpdateWithRequestBuilder(body: body, _id: _id).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     - PUT /home/{id}/

     - BASIC:
       - type: http
       - name: basicAuth
     - API Key:
       - type: apiKey sessionid (QUERY)
       - name: cookieAuth
     - examples: [{contentType=application/json, example={
  "created_at" : "2000-01-23",
  "brand" : "brand",
  "specifications" : "specifications"
}}]
     - parameter body: (body)
     - parameter _id: (path) A unique integer value identifying this car sale.

     - returns: RequestBuilder<Car>
     */
    open class func homeUpdateWithRequestBuilder(body: Car, _id: Int) -> RequestBuilder<Car> {
        var path = "/home/{id}/"
        let _idPreEscape = "\(_id)"
        let _idPostEscape = _idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{id}", with: _idPostEscape, options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: body)
        let url = URLComponents(string: URLString)


        let requestBuilder: RequestBuilder<Car>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "PUT", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }
    /**

     - parameter brand2: (form)
     - parameter specifications2: (form)
     - parameter createdAt2: (form)
     - parameter brand: (form)
     - parameter specifications: (form)
     - parameter createdAt: (form)
     - parameter _id: (path) A unique integer value identifying this car sale.
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func homeUpdate(brand2: String, specifications2: String, createdAt2: Date, brand: String, specifications: String, createdAt: Date, _id: Int, completion: @escaping ((_ data: Car?,_ error: Error?) -> Void)) {
        homeUpdateWithRequestBuilder(brand2: brand2, specifications2: specifications2, createdAt2: createdAt2, brand: brand, specifications: specifications, createdAt: createdAt, _id: _id).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     - PUT /home/{id}/

     - BASIC:
       - type: http
       - name: basicAuth
     - API Key:
       - type: apiKey sessionid (QUERY)
       - name: cookieAuth
     - examples: [{contentType=application/json, example={
  "created_at" : "2000-01-23",
  "brand" : "brand",
  "specifications" : "specifications"
}}]
     - parameter brand2: (form)
     - parameter specifications2: (form)
     - parameter createdAt2: (form)
     - parameter brand: (form)
     - parameter specifications: (form)
     - parameter createdAt: (form)
     - parameter _id: (path) A unique integer value identifying this car sale.

     - returns: RequestBuilder<Car>
     */
    open class func homeUpdateWithRequestBuilder(brand2: String, specifications2: String, createdAt2: Date, brand: String, specifications: String, createdAt: Date, _id: Int) -> RequestBuilder<Car> {
        var path = "/home/{id}/"
        let _idPreEscape = "\(_id)"
        let _idPostEscape = _idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{id}", with: _idPostEscape, options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: {})
        let url = URLComponents(string: URLString)


        let requestBuilder: RequestBuilder<Car>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "PUT", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }
    /**

     - parameter brand2: (form)
     - parameter specifications2: (form)
     - parameter createdAt2: (form)
     - parameter brand: (form)
     - parameter specifications: (form)
     - parameter createdAt: (form)
     - parameter _id: (path) A unique integer value identifying this car sale.
     - parameter completion: completion handler to receive the data and the error objects
     */



    /**
     - PUT /home/{id}/

     - BASIC:
       - type: http
       - name: basicAuth
     - API Key:
       - type: apiKey sessionid (QUERY)
       - name: cookieAuth
     - examples: [{contentType=application/json, example={
  "created_at" : "2000-01-23",
  "brand" : "brand",
  "specifications" : "specifications"
}}]
     - parameter brand2: (form)
     - parameter specifications2: (form)
     - parameter createdAt2: (form)
     - parameter brand: (form)
     - parameter specifications: (form)
     - parameter createdAt: (form)
     - parameter _id: (path) A unique integer value identifying this car sale.

     - returns: RequestBuilder<Car>
     */

}
