//
// PCMaster.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PCMaster: Codable {

    public var procesador: String
    public var tarjetaGrafica: String
    public var numVentiladores: Int
    public var fuentePoder: String
    public var fechaConsulta: Date

    public init(procesador: String, tarjetaGrafica: String, numVentiladores: Int, fuentePoder: String, fechaConsulta: Date) {
        self.procesador = procesador
        self.tarjetaGrafica = tarjetaGrafica
        self.numVentiladores = numVentiladores
        self.fuentePoder = fuentePoder
        self.fechaConsulta = fechaConsulta
    }

    public enum CodingKeys: String, CodingKey {
        case procesador
        case tarjetaGrafica
        case numVentiladores = "NumVentiladores"
        case fuentePoder = "FuentePoder"
        case fechaConsulta = "FechaConsulta"
    }

}

