//
// HomeAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire


open class HomeAPI {
    /**

     - parameter body: (body)  
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func homeCreate(body: Activity, completion: @escaping ((_ data: Activity?,_ error: Error?) -> Void)) {
        homeCreateWithRequestBuilder(body: body).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     - POST /home/

     - :
       - type: http
       - name: jwtAuth
     - examples: [{contentType=application/json, example={
  "created_at" : "2000-01-23T04:56:07.000+00:00",
  "title" : "title",
  "activity_number" : 0,
  "content" : "content"
}}]
     - parameter body: (body)  

     - returns: RequestBuilder<Activity> 
     */
    open class func homeCreateWithRequestBuilder(body: Activity) -> RequestBuilder<Activity> {
        let path = "/home/"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: body)
        let url = URLComponents(string: URLString)


        let requestBuilder: RequestBuilder<Activity>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }
    /**

     - parameter activityNumber2: (form)  
     - parameter title2: (form)  
     - parameter content2: (form)  
     - parameter createdAt2: (form)  
     - parameter activityNumber: (form)  
     - parameter title: (form)  
     - parameter content: (form)  
     - parameter createdAt: (form)  
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func homeCreate(activityNumber2: Int, title2: String, content2: String, createdAt2: Date, activityNumber: Int, title: String, content: String, createdAt: Date, completion: @escaping ((_ data: Activity?,_ error: Error?) -> Void)) {
        homeCreateWithRequestBuilder(activityNumber2: activityNumber2, title2: title2, content2: content2, createdAt2: createdAt2, activityNumber: activityNumber, title: title, content: content, createdAt: createdAt).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     - POST /home/

     - :
       - type: http
       - name: jwtAuth
     - examples: [{contentType=application/json, example={
  "created_at" : "2000-01-23T04:56:07.000+00:00",
  "title" : "title",
  "activity_number" : 0,
  "content" : "content"
}}]
     - parameter activityNumber2: (form)  
     - parameter title2: (form)  
     - parameter content2: (form)  
     - parameter createdAt2: (form)  
     - parameter activityNumber: (form)  
     - parameter title: (form)  
     - parameter content: (form)  
     - parameter createdAt: (form)  

     - returns: RequestBuilder<Activity> 
     */
    open class func homeCreateWithRequestBuilder(activityNumber2: Int, title2: String, content2: String, createdAt2: Date, activityNumber: Int, title: String, content: String, createdAt: Date) -> RequestBuilder<Activity> {
        let path = "/home/"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: body)
        let url = URLComponents(string: URLString)


        let requestBuilder: RequestBuilder<Activity>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }
    /**

     - parameter activityNumber2: (form)  
     - parameter title2: (form)  
     - parameter content2: (form)  
     - parameter createdAt2: (form)  
     - parameter activityNumber: (form)  
     - parameter title: (form)  
     - parameter content: (form)  
     - parameter createdAt: (form)  
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func homeCreate(activityNumber2: Int, title2: String, content2: String, createdAt2: Date, activityNumber: Int, title: String, content: String, createdAt: Date, completion: @escaping ((_ data: Activity?,_ error: Error?) -> Void)) {
        homeCreateWithRequestBuilder(activityNumber2: activityNumber2, title2: title2, content2: content2, createdAt2: createdAt2, activityNumber: activityNumber, title: title, content: content, createdAt: createdAt).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     - POST /home/

     - :
       - type: http
       - name: jwtAuth
     - examples: [{contentType=application/json, example={
  "created_at" : "2000-01-23T04:56:07.000+00:00",
  "title" : "title",
  "activity_number" : 0,
  "content" : "content"
}}]
     - parameter activityNumber2: (form)  
     - parameter title2: (form)  
     - parameter content2: (form)  
     - parameter createdAt2: (form)  
     - parameter activityNumber: (form)  
     - parameter title: (form)  
     - parameter content: (form)  
     - parameter createdAt: (form)  

     - returns: RequestBuilder<Activity> 
     */
    open class func homeCreateWithRequestBuilder(activityNumber2: Int, title2: String, content2: String, createdAt2: Date, activityNumber: Int, title: String, content: String, createdAt: Date) -> RequestBuilder<Activity> {
        let path = "/home/"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: body)
        let url = URLComponents(string: URLString)


        let requestBuilder: RequestBuilder<Activity>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }
    /**

     - parameter _id: (path) A unique integer value identifying this activity model. 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func homeDestroy(_id: Int, completion: @escaping ((_ data: Void?,_ error: Error?) -> Void)) {
        homeDestroyWithRequestBuilder(_id: _id).execute { (response, error) -> Void in
            if error == nil {
                completion((), error)
            } else {
                completion(nil, error)
            }
        }
    }


    /**
     - DELETE /home/{id}/

     - :
       - type: http
       - name: jwtAuth
     - parameter _id: (path) A unique integer value identifying this activity model. 

     - returns: RequestBuilder<Void> 
     */
    open class func homeDestroyWithRequestBuilder(_id: Int) -> RequestBuilder<Void> {
        var path = "/home/{id}/"
        let _idPreEscape = "\(_id)"
        let _idPostEscape = _idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{id}", with: _idPostEscape, options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        let url = URLComponents(string: URLString)


        let requestBuilder: RequestBuilder<Void>.Type = SwaggerClientAPI.requestBuilderFactory.getNonDecodableBuilder()

        return requestBuilder.init(method: "DELETE", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }
    /**

     - parameter page: (query) A page number within the paginated result set. (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func homeList(page: Int? = nil, completion: @escaping ((_ data: PaginatedActivityList?,_ error: Error?) -> Void)) {
        homeListWithRequestBuilder(page: page).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     - GET /home/

     - :
       - type: http
       - name: jwtAuth
     - examples: [{contentType=application/json, example={
  "next" : "http://api.example.org/accounts/?page=4",
  "previous" : "http://api.example.org/accounts/?page=2",
  "count" : 123,
  "results" : [ {
    "created_at" : "2000-01-23T04:56:07.000+00:00",
    "title" : "title",
    "activity_number" : 0,
    "content" : "content"
  }, {
    "created_at" : "2000-01-23T04:56:07.000+00:00",
    "title" : "title",
    "activity_number" : 0,
    "content" : "content"
  } ]
}}]
     - parameter page: (query) A page number within the paginated result set. (optional)

     - returns: RequestBuilder<PaginatedActivityList> 
     */
    open class func homeListWithRequestBuilder(page: Int? = nil) -> RequestBuilder<PaginatedActivityList> {
        let path = "/home/"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
                        "page": page?.encodeToJSON()
        ])


        let requestBuilder: RequestBuilder<PaginatedActivityList>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }
    /**

     - parameter _id: (path) A unique integer value identifying this activity model. 
     - parameter body: (body)  (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func homePartialUpdate(_id: Int, body: PatchedActivity? = nil, completion: @escaping ((_ data: Activity?,_ error: Error?) -> Void)) {
        homePartialUpdateWithRequestBuilder(_id: _id, body: body).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     - PATCH /home/{id}/

     - :
       - type: http
       - name: jwtAuth
     - examples: [{contentType=application/json, example={
  "created_at" : "2000-01-23T04:56:07.000+00:00",
  "title" : "title",
  "activity_number" : 0,
  "content" : "content"
}}]
     - parameter _id: (path) A unique integer value identifying this activity model. 
     - parameter body: (body)  (optional)

     - returns: RequestBuilder<Activity> 
     */
    open class func homePartialUpdateWithRequestBuilder(_id: Int, body: PatchedActivity? = nil) -> RequestBuilder<Activity> {
        var path = "/home/{id}/"
        let _idPreEscape = "\(_id)"
        let _idPostEscape = _idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{id}", with: _idPostEscape, options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: body)
        let url = URLComponents(string: URLString)


        let requestBuilder: RequestBuilder<Activity>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "PATCH", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }
    /**

     - parameter _id: (path) A unique integer value identifying this activity model. 
     - parameter activityNumber2: (form)  (optional)
     - parameter title2: (form)  (optional)
     - parameter content2: (form)  (optional)
     - parameter createdAt2: (form)  (optional)
     - parameter activityNumber: (form)  (optional)
     - parameter title: (form)  (optional)
     - parameter content: (form)  (optional)
     - parameter createdAt: (form)  (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func homePartialUpdate(_id: Int, activityNumber2: Int? = nil, title2: String? = nil, content2: String? = nil, createdAt2: Date? = nil, activityNumber: Int? = nil, title: String? = nil, content: String? = nil, createdAt: Date? = nil, completion: @escaping ((_ data: Activity?,_ error: Error?) -> Void)) {
        homePartialUpdateWithRequestBuilder(_id: _id, activityNumber2: activityNumber2, title2: title2, content2: content2, createdAt2: createdAt2, activityNumber: activityNumber, title: title, content: content, createdAt: createdAt).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     - PATCH /home/{id}/

     - :
       - type: http
       - name: jwtAuth
     - examples: [{contentType=application/json, example={
  "created_at" : "2000-01-23T04:56:07.000+00:00",
  "title" : "title",
  "activity_number" : 0,
  "content" : "content"
}}]
     - parameter _id: (path) A unique integer value identifying this activity model. 
     - parameter activityNumber2: (form)  (optional)
     - parameter title2: (form)  (optional)
     - parameter content2: (form)  (optional)
     - parameter createdAt2: (form)  (optional)
     - parameter activityNumber: (form)  (optional)
     - parameter title: (form)  (optional)
     - parameter content: (form)  (optional)
     - parameter createdAt: (form)  (optional)

     - returns: RequestBuilder<Activity> 
     */
    open class func homePartialUpdateWithRequestBuilder(_id: Int, activityNumber2: Int? = nil, title2: String? = nil, content2: String? = nil, createdAt2: Date? = nil, activityNumber: Int? = nil, title: String? = nil, content: String? = nil, createdAt: Date? = nil) -> RequestBuilder<Activity> {
        var path = "/home/{id}/"
        let _idPreEscape = "\(_id)"
        let _idPostEscape = _idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{id}", with: _idPostEscape, options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: body)
        let url = URLComponents(string: URLString)


        let requestBuilder: RequestBuilder<Activity>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "PATCH", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }
    /**

     - parameter _id: (path) A unique integer value identifying this activity model. 
     - parameter activityNumber2: (form)  (optional)
     - parameter title2: (form)  (optional)
     - parameter content2: (form)  (optional)
     - parameter createdAt2: (form)  (optional)
     - parameter activityNumber: (form)  (optional)
     - parameter title: (form)  (optional)
     - parameter content: (form)  (optional)
     - parameter createdAt: (form)  (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func homePartialUpdate(_id: Int, activityNumber2: Int? = nil, title2: String? = nil, content2: String? = nil, createdAt2: Date? = nil, activityNumber: Int? = nil, title: String? = nil, content: String? = nil, createdAt: Date? = nil, completion: @escaping ((_ data: Activity?,_ error: Error?) -> Void)) {
        homePartialUpdateWithRequestBuilder(_id: _id, activityNumber2: activityNumber2, title2: title2, content2: content2, createdAt2: createdAt2, activityNumber: activityNumber, title: title, content: content, createdAt: createdAt).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     - PATCH /home/{id}/

     - :
       - type: http
       - name: jwtAuth
     - examples: [{contentType=application/json, example={
  "created_at" : "2000-01-23T04:56:07.000+00:00",
  "title" : "title",
  "activity_number" : 0,
  "content" : "content"
}}]
     - parameter _id: (path) A unique integer value identifying this activity model. 
     - parameter activityNumber2: (form)  (optional)
     - parameter title2: (form)  (optional)
     - parameter content2: (form)  (optional)
     - parameter createdAt2: (form)  (optional)
     - parameter activityNumber: (form)  (optional)
     - parameter title: (form)  (optional)
     - parameter content: (form)  (optional)
     - parameter createdAt: (form)  (optional)

     - returns: RequestBuilder<Activity> 
     */
    open class func homePartialUpdateWithRequestBuilder(_id: Int, activityNumber2: Int? = nil, title2: String? = nil, content2: String? = nil, createdAt2: Date? = nil, activityNumber: Int? = nil, title: String? = nil, content: String? = nil, createdAt: Date? = nil) -> RequestBuilder<Activity> {
        var path = "/home/{id}/"
        let _idPreEscape = "\(_id)"
        let _idPostEscape = _idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{id}", with: _idPostEscape, options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: body)
        let url = URLComponents(string: URLString)


        let requestBuilder: RequestBuilder<Activity>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "PATCH", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }
    /**

     - parameter _id: (path) A unique integer value identifying this activity model. 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func homeRetrieve(_id: Int, completion: @escaping ((_ data: Activity?,_ error: Error?) -> Void)) {
        homeRetrieveWithRequestBuilder(_id: _id).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     - GET /home/{id}/

     - :
       - type: http
       - name: jwtAuth
     - examples: [{contentType=application/json, example={
  "created_at" : "2000-01-23T04:56:07.000+00:00",
  "title" : "title",
  "activity_number" : 0,
  "content" : "content"
}}]
     - parameter _id: (path) A unique integer value identifying this activity model. 

     - returns: RequestBuilder<Activity> 
     */
    open class func homeRetrieveWithRequestBuilder(_id: Int) -> RequestBuilder<Activity> {
        var path = "/home/{id}/"
        let _idPreEscape = "\(_id)"
        let _idPostEscape = _idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{id}", with: _idPostEscape, options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        let url = URLComponents(string: URLString)


        let requestBuilder: RequestBuilder<Activity>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }
    /**

     - parameter body: (body)  
     - parameter _id: (path) A unique integer value identifying this activity model. 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func homeUpdate(body: Activity, _id: Int, completion: @escaping ((_ data: Activity?,_ error: Error?) -> Void)) {
        homeUpdateWithRequestBuilder(body: body, _id: _id).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     - PUT /home/{id}/

     - :
       - type: http
       - name: jwtAuth
     - examples: [{contentType=application/json, example={
  "created_at" : "2000-01-23T04:56:07.000+00:00",
  "title" : "title",
  "activity_number" : 0,
  "content" : "content"
}}]
     - parameter body: (body)  
     - parameter _id: (path) A unique integer value identifying this activity model. 

     - returns: RequestBuilder<Activity> 
     */
    open class func homeUpdateWithRequestBuilder(body: Activity, _id: Int) -> RequestBuilder<Activity> {
        var path = "/home/{id}/"
        let _idPreEscape = "\(_id)"
        let _idPostEscape = _idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{id}", with: _idPostEscape, options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: body)
        let url = URLComponents(string: URLString)


        let requestBuilder: RequestBuilder<Activity>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "PUT", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }
    /**

     - parameter activityNumber2: (form)  
     - parameter title2: (form)  
     - parameter content2: (form)  
     - parameter createdAt2: (form)  
     - parameter activityNumber: (form)  
     - parameter title: (form)  
     - parameter content: (form)  
     - parameter createdAt: (form)  
     - parameter _id: (path) A unique integer value identifying this activity model. 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func homeUpdate(activityNumber2: Int, title2: String, content2: String, createdAt2: Date, activityNumber: Int, title: String, content: String, createdAt: Date, _id: Int, completion: @escaping ((_ data: Activity?,_ error: Error?) -> Void)) {
        homeUpdateWithRequestBuilder(activityNumber2: activityNumber2, title2: title2, content2: content2, createdAt2: createdAt2, activityNumber: activityNumber, title: title, content: content, createdAt: createdAt, _id: _id).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     - PUT /home/{id}/

     - :
       - type: http
       - name: jwtAuth
     - examples: [{contentType=application/json, example={
  "created_at" : "2000-01-23T04:56:07.000+00:00",
  "title" : "title",
  "activity_number" : 0,
  "content" : "content"
}}]
     - parameter activityNumber2: (form)  
     - parameter title2: (form)  
     - parameter content2: (form)  
     - parameter createdAt2: (form)  
     - parameter activityNumber: (form)  
     - parameter title: (form)  
     - parameter content: (form)  
     - parameter createdAt: (form)  
     - parameter _id: (path) A unique integer value identifying this activity model. 

     - returns: RequestBuilder<Activity> 
     */
    open class func homeUpdateWithRequestBuilder(activityNumber2: Int, title2: String, content2: String, createdAt2: Date, activityNumber: Int, title: String, content: String, createdAt: Date, _id: Int) -> RequestBuilder<Activity> {
        var path = "/home/{id}/"
        let _idPreEscape = "\(_id)"
        let _idPostEscape = _idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{id}", with: _idPostEscape, options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: body)
        let url = URLComponents(string: URLString)


        let requestBuilder: RequestBuilder<Activity>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "PUT", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }
    /**

     - parameter activityNumber2: (form)  
     - parameter title2: (form)  
     - parameter content2: (form)  
     - parameter createdAt2: (form)  
     - parameter activityNumber: (form)  
     - parameter title: (form)  
     - parameter content: (form)  
     - parameter createdAt: (form)  
     - parameter _id: (path) A unique integer value identifying this activity model. 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func homeUpdate(activityNumber2: Int, title2: String, content2: String, createdAt2: Date, activityNumber: Int, title: String, content: String, createdAt: Date, _id: Int, completion: @escaping ((_ data: Activity?,_ error: Error?) -> Void)) {
        homeUpdateWithRequestBuilder(activityNumber2: activityNumber2, title2: title2, content2: content2, createdAt2: createdAt2, activityNumber: activityNumber, title: title, content: content, createdAt: createdAt, _id: _id).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     - PUT /home/{id}/

     - :
       - type: http
       - name: jwtAuth
     - examples: [{contentType=application/json, example={
  "created_at" : "2000-01-23T04:56:07.000+00:00",
  "title" : "title",
  "activity_number" : 0,
  "content" : "content"
}}]
     - parameter activityNumber2: (form)  
     - parameter title2: (form)  
     - parameter content2: (form)  
     - parameter createdAt2: (form)  
     - parameter activityNumber: (form)  
     - parameter title: (form)  
     - parameter content: (form)  
     - parameter createdAt: (form)  
     - parameter _id: (path) A unique integer value identifying this activity model. 

     - returns: RequestBuilder<Activity> 
     */
    open class func homeUpdateWithRequestBuilder(activityNumber2: Int, title2: String, content2: String, createdAt2: Date, activityNumber: Int, title: String, content: String, createdAt: Date, _id: Int) -> RequestBuilder<Activity> {
        var path = "/home/{id}/"
        let _idPreEscape = "\(_id)"
        let _idPostEscape = _idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{id}", with: _idPostEscape, options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: body)
        let url = URLComponents(string: URLString)


        let requestBuilder: RequestBuilder<Activity>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "PUT", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }
}
