//
// PatchedActivity.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PatchedActivity: Codable {

    public var activityNumber: Int?
    public var title: String?
    public var content: String?
    public var createdAt: Date?

    public init(activityNumber: Int? = nil, title: String? = nil, content: String? = nil, createdAt: Date? = nil) {
        self.activityNumber = activityNumber
        self.title = title
        self.content = content
        self.createdAt = createdAt
    }

    public enum CodingKeys: String, CodingKey { 
        case activityNumber = "activity_number"
        case title
        case content
        case createdAt = "created_at"
    }

}
