//
// TokenRefresh.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct TokenRefresh: Codable {

    public var access: String
    public var refresh: String

    public init(access: String, refresh: String) {
        self.access = access
        self.refresh = refresh
    }


}
