//
// Activity.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Activity: Codable {

    public var activityNumber: Int
    public var title: String
    public var content: String
    public var createdAt: Date

    public init(activityNumber: Int, title: String, content: String, createdAt: Date) {
        self.activityNumber = activityNumber
        self.title = title
        self.content = content
        self.createdAt = createdAt
    }

    public enum CodingKeys: String, CodingKey { 
        case activityNumber = "activity_number"
        case title
        case content
        case createdAt = "created_at"
    }

}
