//
// CustomAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire


open class CustomAPI {
    /**

     - parameter body: (body)  
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func customCreate(body: CustomSerialier, completion: @escaping ((_ data: CustomSerialier?,_ error: Error?) -> Void)) {
        customCreateWithRequestBuilder(body: body).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     - POST /custom/

     - BASIC:
       - type: http
       - name: basicAuth
     - API Key:
       - type: apiKey sessionid (QUERY)
       - name: cookieAuth
     - :
       - type: http
       - name: jwtAuth
     - API Key:
       - type: apiKey Authorization 
       - name: tokenAuth
     - examples: [{contentType=application/json, example={
  "date" : "2000-01-23",
  "address" : "address",
  "phone" : "phone",
  "name" : "name",
  "last_name" : "last_name",
  "description" : "description",
  "age" : 0,
  "email" : ""
}}]
     - parameter body: (body)  

     - returns: RequestBuilder<CustomSerialier> 
     */
    open class func customCreateWithRequestBuilder(body: CustomSerialier) -> RequestBuilder<CustomSerialier> {
        let path = "/custom/"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: body)
        let url = URLComponents(string: URLString)


        let requestBuilder: RequestBuilder<CustomSerialier>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }
    /**

     - parameter name2: (form)  
     - parameter lastName2: (form)  
     - parameter age2: (form)  
     - parameter email2: (form)  
     - parameter phone2: (form)  
     - parameter address2: (form)  
     - parameter _description2: (form)  
     - parameter date2: (form)  
     - parameter name: (form)  
     - parameter lastName: (form)  
     - parameter age: (form)  
     - parameter email: (form)  
     - parameter phone: (form)  
     - parameter address: (form)  
     - parameter _description: (form)  
     - parameter date: (form)  
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func customCreate(name2: String, lastName2: String, age2: Int, email2: String, phone2: String, address2: String, _description2: String, date2: Date, name: String, lastName: String, age: Int, email: String, phone: String, address: String, _description: String, date: Date, completion: @escaping ((_ data: CustomSerialier?,_ error: Error?) -> Void)) {
        customCreateWithRequestBuilder(name2: name2, lastName2: lastName2, age2: age2, email2: email2, phone2: phone2, address2: address2, _description2: _description2, date2: date2, name: name, lastName: lastName, age: age, email: email, phone: phone, address: address, _description: _description, date: date).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     - POST /custom/

     - BASIC:
       - type: http
       - name: basicAuth
     - API Key:
       - type: apiKey sessionid (QUERY)
       - name: cookieAuth
     - :
       - type: http
       - name: jwtAuth
     - API Key:
       - type: apiKey Authorization 
       - name: tokenAuth
     - examples: [{contentType=application/json, example={
  "date" : "2000-01-23",
  "address" : "address",
  "phone" : "phone",
  "name" : "name",
  "last_name" : "last_name",
  "description" : "description",
  "age" : 0,
  "email" : ""
}}]
     - parameter name2: (form)  
     - parameter lastName2: (form)  
     - parameter age2: (form)  
     - parameter email2: (form)  
     - parameter phone2: (form)  
     - parameter address2: (form)  
     - parameter _description2: (form)  
     - parameter date2: (form)  
     - parameter name: (form)  
     - parameter lastName: (form)  
     - parameter age: (form)  
     - parameter email: (form)  
     - parameter phone: (form)  
     - parameter address: (form)  
     - parameter _description: (form)  
     - parameter date: (form)  

     - returns: RequestBuilder<CustomSerialier> 
     */
    open class func customCreateWithRequestBuilder(name2: String, lastName2: String, age2: Int, email2: String, phone2: String, address2: String, _description2: String, date2: Date, name: String, lastName: String, age: Int, email: String, phone: String, address: String, _description: String, date: Date) -> RequestBuilder<CustomSerialier> {
        let path = "/custom/"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: body)
        let url = URLComponents(string: URLString)


        let requestBuilder: RequestBuilder<CustomSerialier>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }
    /**

     - parameter name2: (form)  
     - parameter lastName2: (form)  
     - parameter age2: (form)  
     - parameter email2: (form)  
     - parameter phone2: (form)  
     - parameter address2: (form)  
     - parameter _description2: (form)  
     - parameter date2: (form)  
     - parameter name: (form)  
     - parameter lastName: (form)  
     - parameter age: (form)  
     - parameter email: (form)  
     - parameter phone: (form)  
     - parameter address: (form)  
     - parameter _description: (form)  
     - parameter date: (form)  
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func customCreate(name2: String, lastName2: String, age2: Int, email2: String, phone2: String, address2: String, _description2: String, date2: Date, name: String, lastName: String, age: Int, email: String, phone: String, address: String, _description: String, date: Date, completion: @escaping ((_ data: CustomSerialier?,_ error: Error?) -> Void)) {
        customCreateWithRequestBuilder(name2: name2, lastName2: lastName2, age2: age2, email2: email2, phone2: phone2, address2: address2, _description2: _description2, date2: date2, name: name, lastName: lastName, age: age, email: email, phone: phone, address: address, _description: _description, date: date).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     - POST /custom/

     - BASIC:
       - type: http
       - name: basicAuth
     - API Key:
       - type: apiKey sessionid (QUERY)
       - name: cookieAuth
     - :
       - type: http
       - name: jwtAuth
     - API Key:
       - type: apiKey Authorization 
       - name: tokenAuth
     - examples: [{contentType=application/json, example={
  "date" : "2000-01-23",
  "address" : "address",
  "phone" : "phone",
  "name" : "name",
  "last_name" : "last_name",
  "description" : "description",
  "age" : 0,
  "email" : ""
}}]
     - parameter name2: (form)  
     - parameter lastName2: (form)  
     - parameter age2: (form)  
     - parameter email2: (form)  
     - parameter phone2: (form)  
     - parameter address2: (form)  
     - parameter _description2: (form)  
     - parameter date2: (form)  
     - parameter name: (form)  
     - parameter lastName: (form)  
     - parameter age: (form)  
     - parameter email: (form)  
     - parameter phone: (form)  
     - parameter address: (form)  
     - parameter _description: (form)  
     - parameter date: (form)  

     - returns: RequestBuilder<CustomSerialier> 
     */
    open class func customCreateWithRequestBuilder(name2: String, lastName2: String, age2: Int, email2: String, phone2: String, address2: String, _description2: String, date2: Date, name: String, lastName: String, age: Int, email: String, phone: String, address: String, _description: String, date: Date) -> RequestBuilder<CustomSerialier> {
        let path = "/custom/"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: body)
        let url = URLComponents(string: URLString)


        let requestBuilder: RequestBuilder<CustomSerialier>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }
    /**

     - parameter _id: (path) A unique integer value identifying this Custom Model. 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func customDestroy(_id: Int, completion: @escaping ((_ data: Void?,_ error: Error?) -> Void)) {
        customDestroyWithRequestBuilder(_id: _id).execute { (response, error) -> Void in
            if error == nil {
                completion((), error)
            } else {
                completion(nil, error)
            }
        }
    }


    /**
     - DELETE /custom/{id}/

     - BASIC:
       - type: http
       - name: basicAuth
     - API Key:
       - type: apiKey sessionid (QUERY)
       - name: cookieAuth
     - :
       - type: http
       - name: jwtAuth
     - API Key:
       - type: apiKey Authorization 
       - name: tokenAuth
     - parameter _id: (path) A unique integer value identifying this Custom Model. 

     - returns: RequestBuilder<Void> 
     */
    open class func customDestroyWithRequestBuilder(_id: Int) -> RequestBuilder<Void> {
        var path = "/custom/{id}/"
        let _idPreEscape = "\(_id)"
        let _idPostEscape = _idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{id}", with: _idPostEscape, options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        let url = URLComponents(string: URLString)


        let requestBuilder: RequestBuilder<Void>.Type = SwaggerClientAPI.requestBuilderFactory.getNonDecodableBuilder()

        return requestBuilder.init(method: "DELETE", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }
    /**

     - parameter page: (query) A page number within the paginated result set. (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func customList(page: Int? = nil, completion: @escaping ((_ data: PaginatedCustomSerialierList?,_ error: Error?) -> Void)) {
        customListWithRequestBuilder(page: page).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     - GET /custom/

     - BASIC:
       - type: http
       - name: basicAuth
     - API Key:
       - type: apiKey sessionid (QUERY)
       - name: cookieAuth
     - :
       - type: http
       - name: jwtAuth
     - API Key:
       - type: apiKey Authorization 
       - name: tokenAuth
     - examples: [{contentType=application/json, example={
  "next" : "http://api.example.org/accounts/?page=4",
  "previous" : "http://api.example.org/accounts/?page=2",
  "count" : 123,
  "results" : [ {
    "date" : "2000-01-23",
    "address" : "address",
    "phone" : "phone",
    "name" : "name",
    "last_name" : "last_name",
    "description" : "description",
    "age" : 0,
    "email" : ""
  }, {
    "date" : "2000-01-23",
    "address" : "address",
    "phone" : "phone",
    "name" : "name",
    "last_name" : "last_name",
    "description" : "description",
    "age" : 0,
    "email" : ""
  } ]
}}]
     - parameter page: (query) A page number within the paginated result set. (optional)

     - returns: RequestBuilder<PaginatedCustomSerialierList> 
     */
    open class func customListWithRequestBuilder(page: Int? = nil) -> RequestBuilder<PaginatedCustomSerialierList> {
        let path = "/custom/"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
                        "page": page?.encodeToJSON()
        ])


        let requestBuilder: RequestBuilder<PaginatedCustomSerialierList>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }
    /**

     - parameter _id: (path) A unique integer value identifying this Custom Model. 
     - parameter body: (body)  (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func customPartialUpdate(_id: Int, body: PatchedCustomSerialier? = nil, completion: @escaping ((_ data: CustomSerialier?,_ error: Error?) -> Void)) {
        customPartialUpdateWithRequestBuilder(_id: _id, body: body).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     - PATCH /custom/{id}/

     - BASIC:
       - type: http
       - name: basicAuth
     - API Key:
       - type: apiKey sessionid (QUERY)
       - name: cookieAuth
     - :
       - type: http
       - name: jwtAuth
     - API Key:
       - type: apiKey Authorization 
       - name: tokenAuth
     - examples: [{contentType=application/json, example={
  "date" : "2000-01-23",
  "address" : "address",
  "phone" : "phone",
  "name" : "name",
  "last_name" : "last_name",
  "description" : "description",
  "age" : 0,
  "email" : ""
}}]
     - parameter _id: (path) A unique integer value identifying this Custom Model. 
     - parameter body: (body)  (optional)

     - returns: RequestBuilder<CustomSerialier> 
     */
    open class func customPartialUpdateWithRequestBuilder(_id: Int, body: PatchedCustomSerialier? = nil) -> RequestBuilder<CustomSerialier> {
        var path = "/custom/{id}/"
        let _idPreEscape = "\(_id)"
        let _idPostEscape = _idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{id}", with: _idPostEscape, options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: body)
        let url = URLComponents(string: URLString)


        let requestBuilder: RequestBuilder<CustomSerialier>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "PATCH", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }
    /**

     - parameter _id: (path) A unique integer value identifying this Custom Model. 
     - parameter name2: (form)  (optional)
     - parameter lastName2: (form)  (optional)
     - parameter age2: (form)  (optional)
     - parameter email2: (form)  (optional)
     - parameter phone2: (form)  (optional)
     - parameter address2: (form)  (optional)
     - parameter _description2: (form)  (optional)
     - parameter date2: (form)  (optional)
     - parameter name: (form)  (optional)
     - parameter lastName: (form)  (optional)
     - parameter age: (form)  (optional)
     - parameter email: (form)  (optional)
     - parameter phone: (form)  (optional)
     - parameter address: (form)  (optional)
     - parameter _description: (form)  (optional)
     - parameter date: (form)  (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func customPartialUpdate(_id: Int, name2: String? = nil, lastName2: String? = nil, age2: Int? = nil, email2: String? = nil, phone2: String? = nil, address2: String? = nil, _description2: String? = nil, date2: Date? = nil, name: String? = nil, lastName: String? = nil, age: Int? = nil, email: String? = nil, phone: String? = nil, address: String? = nil, _description: String? = nil, date: Date? = nil, completion: @escaping ((_ data: CustomSerialier?,_ error: Error?) -> Void)) {
        customPartialUpdateWithRequestBuilder(_id: _id, name2: name2, lastName2: lastName2, age2: age2, email2: email2, phone2: phone2, address2: address2, _description2: _description2, date2: date2, name: name, lastName: lastName, age: age, email: email, phone: phone, address: address, _description: _description, date: date).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     - PATCH /custom/{id}/

     - BASIC:
       - type: http
       - name: basicAuth
     - API Key:
       - type: apiKey sessionid (QUERY)
       - name: cookieAuth
     - :
       - type: http
       - name: jwtAuth
     - API Key:
       - type: apiKey Authorization 
       - name: tokenAuth
     - examples: [{contentType=application/json, example={
  "date" : "2000-01-23",
  "address" : "address",
  "phone" : "phone",
  "name" : "name",
  "last_name" : "last_name",
  "description" : "description",
  "age" : 0,
  "email" : ""
}}]
     - parameter _id: (path) A unique integer value identifying this Custom Model. 
     - parameter name2: (form)  (optional)
     - parameter lastName2: (form)  (optional)
     - parameter age2: (form)  (optional)
     - parameter email2: (form)  (optional)
     - parameter phone2: (form)  (optional)
     - parameter address2: (form)  (optional)
     - parameter _description2: (form)  (optional)
     - parameter date2: (form)  (optional)
     - parameter name: (form)  (optional)
     - parameter lastName: (form)  (optional)
     - parameter age: (form)  (optional)
     - parameter email: (form)  (optional)
     - parameter phone: (form)  (optional)
     - parameter address: (form)  (optional)
     - parameter _description: (form)  (optional)
     - parameter date: (form)  (optional)

     - returns: RequestBuilder<CustomSerialier> 
     */
    open class func customPartialUpdateWithRequestBuilder(_id: Int, name2: String? = nil, lastName2: String? = nil, age2: Int? = nil, email2: String? = nil, phone2: String? = nil, address2: String? = nil, _description2: String? = nil, date2: Date? = nil, name: String? = nil, lastName: String? = nil, age: Int? = nil, email: String? = nil, phone: String? = nil, address: String? = nil, _description: String? = nil, date: Date? = nil) -> RequestBuilder<CustomSerialier> {
        var path = "/custom/{id}/"
        let _idPreEscape = "\(_id)"
        let _idPostEscape = _idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{id}", with: _idPostEscape, options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: body)
        let url = URLComponents(string: URLString)


        let requestBuilder: RequestBuilder<CustomSerialier>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "PATCH", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }
    /**

     - parameter _id: (path) A unique integer value identifying this Custom Model. 
     - parameter name2: (form)  (optional)
     - parameter lastName2: (form)  (optional)
     - parameter age2: (form)  (optional)
     - parameter email2: (form)  (optional)
     - parameter phone2: (form)  (optional)
     - parameter address2: (form)  (optional)
     - parameter _description2: (form)  (optional)
     - parameter date2: (form)  (optional)
     - parameter name: (form)  (optional)
     - parameter lastName: (form)  (optional)
     - parameter age: (form)  (optional)
     - parameter email: (form)  (optional)
     - parameter phone: (form)  (optional)
     - parameter address: (form)  (optional)
     - parameter _description: (form)  (optional)
     - parameter date: (form)  (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func customPartialUpdate(_id: Int, name2: String? = nil, lastName2: String? = nil, age2: Int? = nil, email2: String? = nil, phone2: String? = nil, address2: String? = nil, _description2: String? = nil, date2: Date? = nil, name: String? = nil, lastName: String? = nil, age: Int? = nil, email: String? = nil, phone: String? = nil, address: String? = nil, _description: String? = nil, date: Date? = nil, completion: @escaping ((_ data: CustomSerialier?,_ error: Error?) -> Void)) {
        customPartialUpdateWithRequestBuilder(_id: _id, name2: name2, lastName2: lastName2, age2: age2, email2: email2, phone2: phone2, address2: address2, _description2: _description2, date2: date2, name: name, lastName: lastName, age: age, email: email, phone: phone, address: address, _description: _description, date: date).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     - PATCH /custom/{id}/

     - BASIC:
       - type: http
       - name: basicAuth
     - API Key:
       - type: apiKey sessionid (QUERY)
       - name: cookieAuth
     - :
       - type: http
       - name: jwtAuth
     - API Key:
       - type: apiKey Authorization 
       - name: tokenAuth
     - examples: [{contentType=application/json, example={
  "date" : "2000-01-23",
  "address" : "address",
  "phone" : "phone",
  "name" : "name",
  "last_name" : "last_name",
  "description" : "description",
  "age" : 0,
  "email" : ""
}}]
     - parameter _id: (path) A unique integer value identifying this Custom Model. 
     - parameter name2: (form)  (optional)
     - parameter lastName2: (form)  (optional)
     - parameter age2: (form)  (optional)
     - parameter email2: (form)  (optional)
     - parameter phone2: (form)  (optional)
     - parameter address2: (form)  (optional)
     - parameter _description2: (form)  (optional)
     - parameter date2: (form)  (optional)
     - parameter name: (form)  (optional)
     - parameter lastName: (form)  (optional)
     - parameter age: (form)  (optional)
     - parameter email: (form)  (optional)
     - parameter phone: (form)  (optional)
     - parameter address: (form)  (optional)
     - parameter _description: (form)  (optional)
     - parameter date: (form)  (optional)

     - returns: RequestBuilder<CustomSerialier> 
     */
    open class func customPartialUpdateWithRequestBuilder(_id: Int, name2: String? = nil, lastName2: String? = nil, age2: Int? = nil, email2: String? = nil, phone2: String? = nil, address2: String? = nil, _description2: String? = nil, date2: Date? = nil, name: String? = nil, lastName: String? = nil, age: Int? = nil, email: String? = nil, phone: String? = nil, address: String? = nil, _description: String? = nil, date: Date? = nil) -> RequestBuilder<CustomSerialier> {
        var path = "/custom/{id}/"
        let _idPreEscape = "\(_id)"
        let _idPostEscape = _idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{id}", with: _idPostEscape, options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: body)
        let url = URLComponents(string: URLString)


        let requestBuilder: RequestBuilder<CustomSerialier>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "PATCH", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }
    /**

     - parameter _id: (path) A unique integer value identifying this Custom Model. 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func customRetrieve(_id: Int, completion: @escaping ((_ data: CustomSerialier?,_ error: Error?) -> Void)) {
        customRetrieveWithRequestBuilder(_id: _id).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     - GET /custom/{id}/

     - BASIC:
       - type: http
       - name: basicAuth
     - API Key:
       - type: apiKey sessionid (QUERY)
       - name: cookieAuth
     - :
       - type: http
       - name: jwtAuth
     - API Key:
       - type: apiKey Authorization 
       - name: tokenAuth
     - examples: [{contentType=application/json, example={
  "date" : "2000-01-23",
  "address" : "address",
  "phone" : "phone",
  "name" : "name",
  "last_name" : "last_name",
  "description" : "description",
  "age" : 0,
  "email" : ""
}}]
     - parameter _id: (path) A unique integer value identifying this Custom Model. 

     - returns: RequestBuilder<CustomSerialier> 
     */
    open class func customRetrieveWithRequestBuilder(_id: Int) -> RequestBuilder<CustomSerialier> {
        var path = "/custom/{id}/"
        let _idPreEscape = "\(_id)"
        let _idPostEscape = _idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{id}", with: _idPostEscape, options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        let url = URLComponents(string: URLString)


        let requestBuilder: RequestBuilder<CustomSerialier>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }
    /**

     - parameter body: (body)  
     - parameter _id: (path) A unique integer value identifying this Custom Model. 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func customUpdate(body: CustomSerialier, _id: Int, completion: @escaping ((_ data: CustomSerialier?,_ error: Error?) -> Void)) {
        customUpdateWithRequestBuilder(body: body, _id: _id).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     - PUT /custom/{id}/

     - BASIC:
       - type: http
       - name: basicAuth
     - API Key:
       - type: apiKey sessionid (QUERY)
       - name: cookieAuth
     - :
       - type: http
       - name: jwtAuth
     - API Key:
       - type: apiKey Authorization 
       - name: tokenAuth
     - examples: [{contentType=application/json, example={
  "date" : "2000-01-23",
  "address" : "address",
  "phone" : "phone",
  "name" : "name",
  "last_name" : "last_name",
  "description" : "description",
  "age" : 0,
  "email" : ""
}}]
     - parameter body: (body)  
     - parameter _id: (path) A unique integer value identifying this Custom Model. 

     - returns: RequestBuilder<CustomSerialier> 
     */
    open class func customUpdateWithRequestBuilder(body: CustomSerialier, _id: Int) -> RequestBuilder<CustomSerialier> {
        var path = "/custom/{id}/"
        let _idPreEscape = "\(_id)"
        let _idPostEscape = _idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{id}", with: _idPostEscape, options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: body)
        let url = URLComponents(string: URLString)


        let requestBuilder: RequestBuilder<CustomSerialier>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "PUT", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }
    /**

     - parameter name2: (form)  
     - parameter lastName2: (form)  
     - parameter age2: (form)  
     - parameter email2: (form)  
     - parameter phone2: (form)  
     - parameter address2: (form)  
     - parameter _description2: (form)  
     - parameter date2: (form)  
     - parameter name: (form)  
     - parameter lastName: (form)  
     - parameter age: (form)  
     - parameter email: (form)  
     - parameter phone: (form)  
     - parameter address: (form)  
     - parameter _description: (form)  
     - parameter date: (form)  
     - parameter _id: (path) A unique integer value identifying this Custom Model. 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func customUpdate(name2: String, lastName2: String, age2: Int, email2: String, phone2: String, address2: String, _description2: String, date2: Date, name: String, lastName: String, age: Int, email: String, phone: String, address: String, _description: String, date: Date, _id: Int, completion: @escaping ((_ data: CustomSerialier?,_ error: Error?) -> Void)) {
        customUpdateWithRequestBuilder(name2: name2, lastName2: lastName2, age2: age2, email2: email2, phone2: phone2, address2: address2, _description2: _description2, date2: date2, name: name, lastName: lastName, age: age, email: email, phone: phone, address: address, _description: _description, date: date, _id: _id).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     - PUT /custom/{id}/

     - BASIC:
       - type: http
       - name: basicAuth
     - API Key:
       - type: apiKey sessionid (QUERY)
       - name: cookieAuth
     - :
       - type: http
       - name: jwtAuth
     - API Key:
       - type: apiKey Authorization 
       - name: tokenAuth
     - examples: [{contentType=application/json, example={
  "date" : "2000-01-23",
  "address" : "address",
  "phone" : "phone",
  "name" : "name",
  "last_name" : "last_name",
  "description" : "description",
  "age" : 0,
  "email" : ""
}}]
     - parameter name2: (form)  
     - parameter lastName2: (form)  
     - parameter age2: (form)  
     - parameter email2: (form)  
     - parameter phone2: (form)  
     - parameter address2: (form)  
     - parameter _description2: (form)  
     - parameter date2: (form)  
     - parameter name: (form)  
     - parameter lastName: (form)  
     - parameter age: (form)  
     - parameter email: (form)  
     - parameter phone: (form)  
     - parameter address: (form)  
     - parameter _description: (form)  
     - parameter date: (form)  
     - parameter _id: (path) A unique integer value identifying this Custom Model. 

     - returns: RequestBuilder<CustomSerialier> 
     */
    open class func customUpdateWithRequestBuilder(name2: String, lastName2: String, age2: Int, email2: String, phone2: String, address2: String, _description2: String, date2: Date, name: String, lastName: String, age: Int, email: String, phone: String, address: String, _description: String, date: Date, _id: Int) -> RequestBuilder<CustomSerialier> {
        var path = "/custom/{id}/"
        let _idPreEscape = "\(_id)"
        let _idPostEscape = _idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{id}", with: _idPostEscape, options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: body)
        let url = URLComponents(string: URLString)


        let requestBuilder: RequestBuilder<CustomSerialier>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "PUT", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }
    /**

     - parameter name2: (form)  
     - parameter lastName2: (form)  
     - parameter age2: (form)  
     - parameter email2: (form)  
     - parameter phone2: (form)  
     - parameter address2: (form)  
     - parameter _description2: (form)  
     - parameter date2: (form)  
     - parameter name: (form)  
     - parameter lastName: (form)  
     - parameter age: (form)  
     - parameter email: (form)  
     - parameter phone: (form)  
     - parameter address: (form)  
     - parameter _description: (form)  
     - parameter date: (form)  
     - parameter _id: (path) A unique integer value identifying this Custom Model. 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func customUpdate(name2: String, lastName2: String, age2: Int, email2: String, phone2: String, address2: String, _description2: String, date2: Date, name: String, lastName: String, age: Int, email: String, phone: String, address: String, _description: String, date: Date, _id: Int, completion: @escaping ((_ data: CustomSerialier?,_ error: Error?) -> Void)) {
        customUpdateWithRequestBuilder(name2: name2, lastName2: lastName2, age2: age2, email2: email2, phone2: phone2, address2: address2, _description2: _description2, date2: date2, name: name, lastName: lastName, age: age, email: email, phone: phone, address: address, _description: _description, date: date, _id: _id).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     - PUT /custom/{id}/

     - BASIC:
       - type: http
       - name: basicAuth
     - API Key:
       - type: apiKey sessionid (QUERY)
       - name: cookieAuth
     - :
       - type: http
       - name: jwtAuth
     - API Key:
       - type: apiKey Authorization 
       - name: tokenAuth
     - examples: [{contentType=application/json, example={
  "date" : "2000-01-23",
  "address" : "address",
  "phone" : "phone",
  "name" : "name",
  "last_name" : "last_name",
  "description" : "description",
  "age" : 0,
  "email" : ""
}}]
     - parameter name2: (form)  
     - parameter lastName2: (form)  
     - parameter age2: (form)  
     - parameter email2: (form)  
     - parameter phone2: (form)  
     - parameter address2: (form)  
     - parameter _description2: (form)  
     - parameter date2: (form)  
     - parameter name: (form)  
     - parameter lastName: (form)  
     - parameter age: (form)  
     - parameter email: (form)  
     - parameter phone: (form)  
     - parameter address: (form)  
     - parameter _description: (form)  
     - parameter date: (form)  
     - parameter _id: (path) A unique integer value identifying this Custom Model. 

     - returns: RequestBuilder<CustomSerialier> 
     */
    open class func customUpdateWithRequestBuilder(name2: String, lastName2: String, age2: Int, email2: String, phone2: String, address2: String, _description2: String, date2: Date, name: String, lastName: String, age: Int, email: String, phone: String, address: String, _description: String, date: Date, _id: Int) -> RequestBuilder<CustomSerialier> {
        var path = "/custom/{id}/"
        let _idPreEscape = "\(_id)"
        let _idPostEscape = _idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{id}", with: _idPostEscape, options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: body)
        let url = URLComponents(string: URLString)


        let requestBuilder: RequestBuilder<CustomSerialier>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "PUT", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }
}
